src/Simu.App/ViewModels/DadoViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Simu.App.ViewModels
{
    public class DadoViewModel
    {
        [Key]
        public Guid Id { get; set; }
        [HiddenInput]
        public Guid UserId { get; set; }

        [DisplayName("Questões Respondidas")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public int Respondidas { get; set; }

        [DisplayName("Questões acertadas")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public int Acertos { get; set; }

        [DisplayName("Questões errdas")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public int Erros { get; set; }

        [DisplayName("Ano da Prova")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public int AnoProva { get; set; }

    }
}

src/Simu.App/ViewModels/ProvaViewModel.cs
using Simu.App.ViewModels;
using Simu.Business.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Simu.App.ViewModels
{
    public class ProvaViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [DisplayName("Questão")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(10000, ErrorMessage = "O campo {0} precisa ter entre {1} e {2} caracteres", MinimumLength = 1)]
        public Questao Questao { get; set; }

        [ScaffoldColumn(false)]
        public DateTime Data { get; set; }
    }
}

src/Simu.App/Controllers/DadosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Simu.App.ViewModels;
using Simu.Business.Interfaces;
using Simu.Business.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Simu.App.Controllers
{
    [Authorize]
    public class DadosController : BaseController
    {


        private readonly IDadoRepository _dadoRepository;
        private readonly IDadoService _dadoService;
        private readonly IMapper _mapper;

        public DadosController(IMapper mapper,
                                 IDadoRepository dadoRepository,
                                 IDadoService dadoService,
                                 INotificador notificador) : base(notificador)
        {

            _dadoRepository = dadoRepository;
            _dadoService = dadoService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public bool AdicionarDados()
        {
            //int acertos, int erros, int respondidas
            if (TempData["Respondidas"] != null)

            {
                // Necessário TypeCasting para tipos complexos.


            }
            var acertos = TempData["Acertos"];
            var erros = TempData["Erros"];
            var respondidas = TempData["Respondidas"];

            var dadoViewModel = new DadoViewModel
            {
                //Acertos = acertos,
                //Erros = erros,
                //Respondidas = respondidas,
            };

            var dado = _mapper.Map<Dado>(dadoViewModel);
            dado.Id = new Guid();

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            dado.UserId = Guid.Parse(userId);
            _dadoService.Adicionar(dado);

            return true;
        }

    }
}

src/Simu.App/Controllers/ProvasController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Simu.App.ViewModels;
using Simu.Business.Interfaces;
using Simu.Business.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ceTe.DynamicPDF;

namespace Simu.App.Controllers
{
    [Authorize]
    public class ProvasController : BaseController
    {

        private readonly IQuestaoRepository _questaoRepository;
        private readonly IQuestaoService _questaoService;
        private readonly IDadoRepository _dadoRepository;
        private readonly IDadoService _dadoService;
        private readonly IMapper _mapper;

        public ProvasController(IMapper mapper,
                                 IQuestaoRepository questaoRepository,
                                 IQuestaoService questaoService,
                                 IDadoRepository dadoRepository,
                                 IDadoService dadoService,
                                 INotificador notificador) : base(notificador)
        {

            _questaoRepository = questaoRepository;
            _questaoService = questaoService;
            _dadoRepository = dadoRepository;
            _dadoService = dadoService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Questoes()
        {
            return View(_mapper.Map<IList<QuestaoViewModel>>(await _questaoRepository.ObterQuestoes()));

        }
        public async Task<IActionResult> Dados()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var id = Guid.Parse(userId);
            var dado = _mapper.Map<Dado>(await _dadoRepository.ObterDadosUsuario(id));

            var dadoViewModel = new DadoViewModel 
            {
                Acertos = dado.Acertos,
                Erros = dado.Erros,
                Respondidas = dado.Respondidas,
            };

            return View(dadoViewModel);
        }

        public async Task<DadoViewModel> ObterDadosPorAno(int anoProva)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var id = Guid.Parse(userId);

            var dado = _mapper.Map<Dado>(await _dadoRepository.ObterDadosUsuarioPorAno(id, anoProva));

            var dadoViewModel = new DadoViewModel
            {
                Acertos = dado.Acertos,
                Erros = dado.Erros,
                Respondidas = dado.Respondidas,
                AnoProva = dado.AnoProva,
            };

            return dadoViewModel;
        }

        public async Task<IActionResult> QuestoesPorProva(string prova)
        {
            ViewData["Prova"] = prova;
            return View(_mapper.Map<IList<QuestaoViewModel>>(await _questaoRepository.ObterQuestoesProva(prova)));

        }

        public async Task<IActionResult> ObterDadosUsuario()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var id = Guid.Parse(userId);
            return View(_mapper.Map<Dado>(await _dadoRepository.ObterDadosUsuario(id)));

        }

        public IActionResult QuestoesRespondidas(IList<QuestaoViewModel> questaoViewModel)
        {
            return View(questaoViewModel);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> VerificarRespostas(IList<QuestaoViewModel> questaoViewModel)
        {
            var dados = new Dado();

            dados.Acertos = 0;
            dados.Erros = 0;
            dados.Respondidas = 0;
            var listModel = questaoViewModel;
            foreach (var item in listModel)
            {
                var resposta = VerificarAlternativa(item);
                var questao = await _questaoRepository.ObterQuestao(item.Id);
                dados.Respondidas = dados.Respondidas + 1;

                if (questao.Resposta == resposta)
                {
                    item.Correta = true;
                    dados.Acertos = dados.Acertos + 1;
                }
                else
                {
                    item.Correta = false;
                    dados.Erros = dados.Erros + 1;
                }
            }

            TempData["Acertos"] = dados.Acertos;
            TempData["Erros"] = dados.Erros;
            TempData["Respondidas"] = dados.Respondidas;

            AdicionarDados(dados);
            return View(listModel);
        }
        private string VerificarAlternativa(QuestaoViewModel model)
        {
            var resposta = "";
            switch (model.Marcada)
            {
                case "A":
                    resposta = model.A;
                    break;
                case "B":
                    resposta = model.B;
                    break;
                case "C":
                    resposta = model.C;
                    break;
                case "D":
                    resposta = model.D;
                    break;
                case "E":
                    resposta = model.E;
                    break;
            }
            return resposta;
        }

        public bool AdicionarDados(Dado dado)
        {
            dado.Id = new Guid();

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            dado.UserId = Guid.Parse(userId);
            _dadoService.Adicionar(dado);

            return true;
        }
    }
}

src/Simu.App/Views/Provas/Dados.cshtml
@model Simu.App.ViewModels.DadoViewModel

@{
    ViewData["Title"] = "Lista de Tarefas Feitas";
}

<head>
    <!-- Carrega a API Google JSAPI -->
    <script type="text/javascript" src="https://www.google.com/jsapi "></script>
    <script type="text/javascript">

        // Carrega as bibliotecas Google Visualization e as específicas para
        //montagem do gráfico
        google.load('visualization', '1.0', { 'packages': ['corechart'] });

        // Faz com que o desenho do gráfico seja feito logo depois que as
        //bibliotecas estiverem carregadas
        // google.setOnLoadCallback(drawChart);

        // Função que cria e popula uma tabela e cria e desenha um gráfico
        //com os dados da tabela
        function drawChart() {

            // Cria a tabela
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Linguagem'); //Adiciona a coluna 'Linguagem'
            data.addColumn('number', 'Porcentagem');//Adiciona coluna 'Porcentagem'
            data.addRows([ //Adiciona as linhas da tabela com os valores
            ['Corretas', @Html.Display("Acertos")],
            ['Incorretas', @Html.Display("Erros")]
            ]);

            // Configura título, largura e altura do gráfico
            var options = {
                title: 'Questões Repondidas',
                width: 800,
                height: 500,
                is3D: true,
                legend: 'left',
                fontSize: 15,
                backgroundColor: 'Gainsboro',
                // chartArea: { 'backgroundColor': 'Gainsboro' },
                backgroundColor: {
                    stroke: 'Gainsboro',
                    strokeWidth: 2
                },
            };
            // Instancia e desenha o gráfico, passando os dados e as opções
            var chart = new google.visualization.PieChart(document.getElementById
                ('chart_div'));
            options.backgor
            chart.draw(data, options);
        }

        google.charts.load('current', { 'packages': ['bar'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart1() {

            // Cria a tabela
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Linguagem'); //Adiciona a coluna 'Linguagem'
            data.addColumn('number', 'Porcentagem');//Adiciona coluna 'Porcentagem'
            data.addRows([ //Adiciona as linhas da tabela com os valores
                ['Matemática', 7],
                ['Fundamentos da Computação', 8],
                ['Tecnologia da Computação', 12]
            ]);


            // Configura título, largura e altura do gráfico
            var options = {
                title: 'Questões Repondidas Por Área',
                width: 800,
                height: 500,
                is3D: true,
                legend: 'left',
                fontSize: 15,
                backgroundColor: 'Gainsboro',
                // chartArea: { 'backgroundColor': 'Gainsboro' },
                backgroundColor: {
                    stroke: 'Gainsboro',
                    strokeWidth: 2
                },
            };
            // Instancia e desenha o gráfico, passando os dados e as opções
            var chart = new google.visualization.PieChart(document.getElementById
                ('chart_div1'));
            chart.draw(data, options);
        }

        google.charts.load('current', { 'packages': ['bar'] });
        google.charts.setOnLoadCallback(drawChart1);

        function drawVisualization() {
            // Some raw data (not necessarily accurate)
            var data = google.visualization.arrayToDataTable([
                ['Year', 'Corretas', 'Incorretas'],
                ['2016', 37, 33],
                ['2017', 50, 20],
                ['2018', 41, 29],
                ['2019', 56, 14]
            ]);

            var options = {
                title: 'Questões Repondidas Por Ano Da Prova',
                vAxis: { title: 'Questões' },
                hAxis: { title: 'Ano' },
                seriesType: 'bars',
                series: { 5: { type: 'line' } },
                width: 800,
                height: 500,
                backgroundColor: 'Gainsboro',
                // chartArea: { 'backgroundColor': 'Gainsboro' },
                backgroundColor: {
                    stroke: 'Gainsboro',
                    strokeWidth: 2
                },

            };


            var chart = new google.visualization.ComboChart(document.getElementById('columnchart_material'));
            chart.draw(data, options);
        }
        google.charts.load('current', { 'packages': ['bar'] });
        google.charts.setOnLoadCallback(drawVisualization);
    </script>
</head>


<!-- O gráfico ficará nesta Div -->
<div class="row justify-content-center">
    <div class="col-xl-3 col-md-6">
        <div class="card card-stats">
            <!-- Card body -->
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title justify-content-center text-uppercase text-muted mb-0">Respondidas</h5>
                        <span class="h2 font-weight-bold mb-0">
                            @Html.Display("Respondidas")
                        </span>
                    </div>
                    <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="ni ni-active-40"></i>
                        </div>
                    </div>
                </div>
                @*<p class="mt-3 mb-0 text-sm">
                        <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                        <span class="text-nowrap">Since last month</span>
                    </p>*@
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card card-stats">
            <!-- Card body -->
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">Corretas</h5>
                        <span class="h2 font-weight-bold mb-0  text-success">
                            @Html.Display("Acertos")
                        </span>
                    </div>
                    <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-orange text-white rounded-circle shadow">
                            <i class="ni ni-chart-pie-35"></i>
                        </div>
                    </div>
                </div>
                @*<p class="mt-3 mb-0 text-sm">
                        <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                        <span class="text-nowrap">Since last month</span>
                    </p>*@
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6">
        <div class="card card-stats">
            <!-- Card body -->
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">Incorretas</h5>
                        <span class="h2 font-weight-bold mb-0  text-danger">
                          @Html.Display("Erros")
                        </span>

                    </div>
                    <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-green text-white rounded-circle shadow">
                            <i class="ni ni-money-coins"></i>
                        </div>
                    </div>
                </div>
                <!--<p class="mt-3 mb-0 text-sm">-->
                @*<span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                    <span class="text-nowrap">Since last month</span>*@
                <!--</p>-->
            </div>
        </div>
    </div>

</div>


<div class="row justify-content-center" id="chart_div" style="width: 800px; height: 500px; margin-left: auto; margin-right: auto; position: relative; margin-top:30px"></div>
<div class="row justify-content-center" id="chart_div1" style="width: 800px; height: 500px; margin-left: auto; margin-right: auto; position: relative; margin-top: 30px "></div>
<div class="row justify-content-center" id="columnchart_material" style="width: 800px; height: 500px; margin-left: auto; margin-right: auto; position: relative; margin-top: 30px "></div>

src/Simu.App/Views/Provas/Index.cshtml
@model IEnumerable<Simu.App.ViewModels.TarefaViewModel>

@{
    ViewData["Title"] = "Lista de Tarefas à Fazer";
}

<h1>@ViewData["Title"]</h1>
<br />
<br />
<vc:Summary></vc:Summary>


<p>
    <a asp-action="Create" class="btn btn-info">Nova Tarefa</a>
</p>
<br />


<div id="TarefaTarget">
    <partial name="_ListarTarefas" />
</div>

<div id="myModal" class="modal fade in">
        <div class="modal-dialog">
            <div class="modal-content">
                <div id="myModalContent"></div>
            </div>
        </div>
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {
            AjaxModal();
        });
    </script>

}

src/Simu.App/Views/Provas/Questoes.cshtml
@model IList<Simu.App.ViewModels.QuestaoViewModel>
@using (Html.BeginForm("VerificarRespostas", "Provas", FormMethod.Post))
{
    ViewData["Title"] = "Questoes";


    <div class="card">
        <div class="card-body">
            <h1>Simulação POSCOMP</h1>
            <h2>Questões aleatórias das avaliações mais recentes.</h2>
        </div>
    </div>

    <br />
    <br />

    @for (var i = 0; i < Model.Count(); ++i)
    {
        <div class="container p-3 my-3 border">
            <div class="card-header">
                Prova POSCOMP @Html.DisplayFor(model => model[i].Prova) - Pergunta  @Html.DisplayFor(model => model[i].Numero)
            </div>
            <div class="container p-3 my-3 border">
                <i class="bi bi-caret-right"></i>

                <blockquote class="blockquote mb-0">
                    @Html.DisplayFor(model => model[i].Enunciado)
                </blockquote>
            </div>
            <br />

            <div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "A")
                        @Html.DisplayFor(model => model[i].A)
                    </li>
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "B")
                        @Html.DisplayFor(model => model[i].B)
                    </li>
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "C")
                        @Html.DisplayFor(model => model[i].C)
                    </li>
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "D")
                        @Html.DisplayFor(model => model[i].D)
                    </li>
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "E")
                        @Html.DisplayFor(model => model[i].E)
                    </li>
                </ul>
            </div>

            @Html.HiddenFor(model => model[i].Id)
            @Html.HiddenFor(model => model[i].TarefaId)
            @Html.HiddenFor(model => model[i].AnoProva)
            @Html.HiddenFor(model => model[i].Numero)
            @Html.HiddenFor(model => model[i].Resposta)
            @Html.HiddenFor(model => model[i].Enunciado)
            @Html.HiddenFor(model => model[i].TipoAssunto)
            @Html.HiddenFor(model => model[i].Prova)
            @Html.HiddenFor(model => model[i].A)
            @Html.HiddenFor(model => model[i].B)
            @Html.HiddenFor(model => model[i].C)
            @Html.HiddenFor(model => model[i].D)
            @Html.HiddenFor(model => model[i].E)


        </div>
    }
    <div>
        <input asp-action="VerificarRespostas" type="submit" value="Finalizar simulado" class="btn btn-success btn-lg" id="ddd" />
    </div>
    <br />
    <br />

    <div>

        <a asp-action="Index">Escolher outra prova</a>
    </div>
}

src/Simu.App/Views/Provas/QuestoesPorProva.cshtml
@model IList<Simu.App.ViewModels.QuestaoViewModel>
@using (Html.BeginForm("VerificarRespostas", "Provas", FormMethod.Post))
{
    ViewData["Title"] = "Questoes";


<div class="card">
    <div class="card-body">
        <h1>POSCOMP @Html.Display("AnoProva")</h1>
        <h2>Simulado do Exame Nacional para Ingresso na Pós-Graduação em Computação.</h2>
    </div>
</div>

    <br />
    <br />

    @for (var i = 0; i < Model.Count(); ++i)
    {
        <div class="container p-3 my-3 border">
            <div>
                <div class="card-header">
                    Pergunta  @Html.DisplayFor(model => model[i].Numero)
                </div>
                <div class="container p-3 my-3 border">
                    <blockquote class="blockquote mb-0">
                        @Html.DisplayFor(model => model[i].Enunciado)
                    </blockquote>
                </div>
            </div>

            <br />

            <div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "A")
                        @Html.DisplayFor(model => model[i].A)
                    </li>
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "B")
                        @Html.DisplayFor(model => model[i].B)
                    </li>
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "C")
                        @Html.DisplayFor(model => model[i].C)
                    </li>
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "D")
                        @Html.DisplayFor(model => model[i].D)
                    </li>
                    <li class="list-group-item">
                        @Html.RadioButtonFor(model => model[i].Marcada, "E")
                        @Html.DisplayFor(model => model[i].E)
                    </li>
                </ul>
            </div>

            @Html.HiddenFor(model => model[i].Id)
            @Html.HiddenFor(model => model[i].TarefaId)
            @Html.HiddenFor(model => model[i].AnoProva)
            @Html.HiddenFor(model => model[i].Numero)
            @Html.HiddenFor(model => model[i].Resposta)
            @Html.HiddenFor(model => model[i].Enunciado)
            @Html.HiddenFor(model => model[i].TipoAssunto)
            @Html.HiddenFor(model => model[i].Prova)
            @Html.HiddenFor(model => model[i].A)
            @Html.HiddenFor(model => model[i].B)
            @Html.HiddenFor(model => model[i].C)
            @Html.HiddenFor(model => model[i].D)
            @Html.HiddenFor(model => model[i].E)


        </div>
    }

    <div>
        <input asp-action="VerificarRespostas" type="submit" value="Finalizar simulado" class="btn btn-success btn-lg" id="ddd" />
    </div>
    <br />
    <br />

    <div>
        <a asp-action="Provas">Escolher outra prova</a>
    </div>
}

src/Simu.App/Views/Provas/VerificarRespostas.cshtml
@model IEnumerable<Simu.App.ViewModels.QuestaoViewModel>
@{ ViewData["Title"] = "Questoes"; }

<div class="card">
    <div class="card-body">
        <h1>Simulado</h1>
        <h3>Exame Nacional para Ingresso na Pós-Graduação em Computação (POSCOMP)</h3>

        <br />
        <div class="alert alert-info" role="alert">
            <h3>Resultado:</h3>
            <h4>
                <a class="btn btn-success" a>
                    <span class="fa fa-check"></span>
                </a>
                Acertos - @TempData["Acertos"]
            </h4>
            <h4>
                <a class="btn btn-danger" a>
                    <span class="fa fa-circle-notch"></span>
                </a>
                Erros - @TempData["Erros"]
            </h4>
        </div>
    </div>
</div>

<br />
<br />

@foreach (var item in Model)
{
    <div class="container p-3 my-3 border">
        <div class="card-header">
            Questão  @Html.DisplayFor(modelItem => item.Numero)
        </div>
        <div class="container p-3 my-3 border">
            <blockquote class="blockquote mb-0">
                @Html.DisplayFor(modelItem => item.Enunciado)
            </blockquote>
        </div>
        <br />

        <div>

            <ul class="list-group list-group-flush">
                @if (item.Resposta == item.A && !item.Correta)
                {
                    <li class="list-group-item">
                        <input class="form-check-input" type="radio" name="radioA" value="@item.A" id="radio_a" disabled>
                        <label class="form-check-label alert alert-dark" for="radioA">
                            @Html.DisplayFor(modelItem => item.A)
                        </label>
                    </li>
                }
                else
                {
                    <li class="list-group-item">
                        <input class="form-check-input" type="radio" name="radioD" value="@item.A" id="radio_a" disabled>
                        <label class="form-check-label" for="radioA">
                            @Html.DisplayFor(modelItem => item.A)
                        </label>
                    </li>
                }
                @if (item.Resposta == item.B && !item.Correta)
                {
                    <li class="list-group-item">
                        <input class="form-check-input" type="radio" name="radioB" value="@item.B" id="radio_b" disabled>
                        <label class="form-check-label alert alert-dark" for="radioB">
                            @Html.DisplayFor(modelItem => item.B)
                        </label>
                    </li>
                }
                else
                {
                    <li class="list-group-item">
                        <input class="form-check-input" type="radio" name="radioB" value="@item.B" id="radio_b" disabled>
                        <label class="form-check-label" for="radioB">
                            @Html.DisplayFor(modelItem => item.B)
                        </label>
                    </li>
                }
                @if (item.Resposta == item.C && !item.Correta)
                {
                    <li class="list-group-item">
                        <input class="form-check-input" type="radio" name="radioC" value="@item.C" id="radio_c" disabled>
                        <label class="form-check-label alert alert-dark" for="radioC">
                            @Html.DisplayFor(modelItem => item.C)
                        </label>
                    </li>
                }
                else
                {
                    <li class="list-group-item">
                        <input class="form-check-input" type="radio" name="radioC" value="@item.C" id="radio_c" disabled>
                        <label class="form-check-label" for="radioC">
                            @Html.DisplayFor(modelItem => item.C)
                        </label>
                    </li>
                }
                @if (item.Resposta == item.D && !item.Correta)
                {
                    <li class="list-group-item">
                        <input class="form-check-input alert" type="radio" name="radioD" value="@item.D" id="radio_d" disabled>
                        <label class="form-check-label alert alert-dark" for="radioD">
                            @Html.DisplayFor(modelItem => item.D)
                        </label>
                    </li>
                }
                else
                {
                    <li class="list-group-item">
                        <input class="form-check-input" type="radio" name="radioD" value="@item.D" id="radio_d" disabled>
                        <label class="form-check-label" for="radioD">
                            @Html.DisplayFor(modelItem => item.D)
                        </label>
                    </li>
                }
                @if (item.Resposta == item.E && !item.Correta)
                {
                    <li class="list-group-item">
                        <input class="form-check-input" type="radio" name="radioA" value="@item.E" id="radio_e" disabled>
                        <label class="form-check-label alert alert-dark" for="radioE">
                            @Html.DisplayFor(modelItem => item.E)
                        </label>
                    </li>
                }
                else
                {
                    <li class="list-group-item">
                        <input class="form-check-input" type="radio" name="radioE" value="@item.E" id="radio_e" disabled>
                        <label class="form-check-label" for="radioE">
                            @Html.DisplayFor(modelItem => item.E)
                        </label>
                    </li>
                }
            </ul>
        </div>

        @if (!item.Correta)
        {
            <div class="alert alert-danger" role="alert" id="correta">
                <h5 class="alert-heading">Resposta incorreta.</h5>
            </div>
        }
        else
        {
            <div class="alert alert-success" role="alert" id="correta">
                <h5 class="alert-heading">Resposta correta!</h5>
                @Html.DisplayFor(modelItem => item.Resposta)
            </div>
        }

    </div>

}

<br />
<br />
<div>
    <input asp-action="Convert" asp-area="Provas" type="submit" value="Processar resultado" class="btn btn-success btn-lg" id="ddd" />
</div>
<div>

    <a asp-action="Index">Escolher outra prova</a>
</div>